#!/bin/bash

endpath="$HOME/.vimconfig"

# Backing up current .vimrc .vimrc.local .vimrc.bundles.local
echo 'backing up current vim config to .vimbak home'
today=`date +%Y%m%d`
#for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $HOME/.vimrc.local $HOME/.vimrc.bundles.local; do [ -e $i ] && mv $i $i.$today; done

# install vundle
if [ ! -d ~/.vim/bundle/vundle ]; then
  echo 'cloning vundle'
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

#
#mkdir -p $endpath/.vim/bundle
ln -sf $endpath/.vimrc $HOME/.vimrc
ln -sf $endpath/.vim $HOME/.vim
ln -sf $endpath/.vimrc.local $HOME/.vimrc.local
ln -sf $endpath/.vimrc.bundles.local $HOME/.vimrc.bundles.local


# install plugins
echo "installing plugins using Vundle"
vim +BundleInstall! +BundleClean +q
