#!/bin/bash
# install vundle
if [ ! -d ~/.vim/bundle/vundle ]; then
  echo 'cloning vundle'
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi
echo 'backup your .vimrc'
#cp ~/.vimrc ~/vimrcbak
#cp ~/.vundle.vim ~/.vundel.vimbak
echo 'copy .vimrc to your home directory'
cp -f .vimrc ~/
cp -f .vundle.vim ~/
echo 'done!'
